version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    groups:
      actions-minor:
        update-types: ["minor", "patch"]

  # Images des manifestes Kubernetes
  - package-ecosystem: "docker"
    directory: "/infra/k8s"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    groups:
      k8s-images-minor:
        update-types: ["minor", "patch"]

  # Providers et modules Terraform.
  - package-ecosystem: "terraform"
    directory: "/infra/terraform"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    groups:
      terraform-minor:
        update-types: ["minor", "patch"]
