name: g4-grafana

services:
  grafana:
    image: ${GRAFANA_IMAGE:-grafana/grafana:latest}
    container_name: g4_grafana_${STAGE}
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - g4_grafana_data:/var/lib/grafana
    networks:
      - g4_net
    ports:
      - "${GRAFANA_PORT}:3000"

volumes:
  g4_grafana_data:
    name: g4_grafana_data_${STAGE}

networks:
  g4_net:
    external: true
